### ISSUE TITLE
Saved replies に設定

### ISSUE THREAD

**Issue by en-tomoda** [tomoda-kazuya/hagukumo.github.io#1]
Reviewer
コメントするときは必ずprefixをつける

目的: レビューコメントの意図や温度感を明確にして、レビュー活動を円滑にする

[ask], [must] を解消することがPullRequest承認の必須条件

[imo], [nits], [comment] はrevieweeに判断が委ねられる任意項目

prefixの種類

must: 修正依頼

Badge: [![must](https://img.shields.io/badge/review-must-red)](https://img.shields.io/badge/review-must-red)

ask: 質問

Badge: [![ask](https://img.shields.io/badge/review-ask-green)](https://img.shields.io/badge/review-ask-green)

imo: 実装提案

Badge: [![imo](https://img.shields.io/badge/review-imo-blue)](https://img.shields.io/badge/review-imo-blue)

nits: 細かい指摘

Badge: [![nits](https://img.shields.io/badge/review-nits-blue)](https://img.shields.io/badge/review-nits-blue)

comment: 上記に当てはまらないコメント

Badge: [![comment](https://img.shields.io/badge/review-comment-lightgray)](https://img.shields.io/badge/review-comment-lightgray)

LGTM: レビューOK

Badge:![Static Badge](https://img.shields.io/badge/review-LGTM-orange?style=flat)

[Saved replies (github.com)](https://github.com/settings/replies)にprefixごとに登録しておくと便利です

**Comment by moooda-dev** [comment]
OKサンキュ
